[package]
name = "bk2d"
version = "0.1.0"
authors = ["71e6fd52 <71e6fd52@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
